=== CoolITSystemsInc/stm32cubeide/stm32cubeide/plugins/com.st.stm32cube.ide.mpu.productdb_1.0.0.201903292002/resources/board_def/stm32TargetDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:stm32="http://openstm32.org/stm32TargetDefinitions"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	targetNamespace="http://openstm32.org/stm32TargetDefinitions"
	xsi:schemaLocation="http://www.w3.org/2001/XMLSchema XMLSchema.xsd"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="2.0">


	<xs:simpleType name="cpuCoreEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="arm7tdmi" />
			<xs:enumeration value="sc100" />
			<xs:enumeration value="arm7tdmi-s" />
			<xs:enumeration value="arm9" />
			<xs:enumeration value="arm920t" />
			<xs:enumeration value="arm922t" />
			<xs:enumeration value="arm926ej-s" />
			<xs:enumeration value="arm946e-s" />
			<xs:enumeration value="arm966e-s" />
			<xs:enumeration value="arm968e-s" />
			<xs:enumeration value="cortex-a5" />
			<xs:enumeration value="arm cortex-a7" />
			<xs:enumeration value="cortex-a7" />
			<xs:enumeration value="cortex-a8" />
			<xs:enumeration value="cortex-a9" />
			<xs:enumeration value="cortex-a12" />
			<xs:enumeration value="cortex-a15" />
			<xs:enumeration value="cortex-a17" />
			<xs:enumeration value="cortex-a53" />
			<xs:enumeration value="cortex-a57" />
			<xs:enumeration value="cortex-a72" />
			<xs:enumeration value="cortex-m0" />
			<xs:enumeration value="arm cortex-m0" />
			<xs:enumeration value="sc000" />
			<xs:enumeration value="arm cortex-m0+" />
			<xs:enumeration value="cortex-m0+" />
			<xs:enumeration value="cortex-m0plus" />
			<xs:enumeration value="arm cortex-m1" />
			<xs:enumeration value="cortex-m1" />
			<xs:enumeration value="arm cortex-m3" />
			<xs:enumeration value="cortex-m3" />
			<xs:enumeration value="sc300" />
			<xs:enumeration value="arm cortex-m4" />
			<xs:enumeration value="cortex-m4" />
			<xs:enumeration value="arm cortex-m7" />
			<xs:enumeration value="cortex-m7" />
			<xs:enumeration value="cortex-m23" />
			<xs:enumeration value="cortex-m33" />
			<xs:enumeration value="cortex-r4" />
			<xs:enumeration value="cortex-r5" />
			<xs:enumeration value="cortex-r7" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="debugDeviceEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="st-linkv1" />
			<xs:enumeration value="st-linkv2" />
			<xs:enumeration value="st-linkv2-1" />
			<xs:enumeration value="st-linkv3" />
			<xs:enumeration value="st-link" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="debugInterfaceEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="swd" />
			<xs:enumeration value="jtag" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="firmwareTypeEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="stdperiph" />
			<xs:enumeration value="hal" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="fpuCoreEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="None" />
			<xs:enumeration value="fpv4-sp-d16" />
			<xs:enumeration value="fpv4_sp_d16" />
			<xs:enumeration value="fpv5-sp-d16" />
			<xs:enumeration value="fpv5_sp_d16" />
			<xs:enumeration value="vfpv3-d32" />
			<xs:enumeration value="vfpv3_d32" />
			<xs:enumeration value="vfpv3-d16" />
			<xs:enumeration value="vfpv3_d16" />
			<xs:enumeration value="vfpv4-d32" />
			<xs:enumeration value="vfpv4_d32" />
			<xs:enumeration value="vfpv4-d16" />
			<xs:enumeration value="vfpv4_d16" />
			<xs:enumeration value="fpv5-d16" />
			<xs:enumeration value="fpv5_d16" />
			<xs:enumeration value="neon-vfpv3" />
			<xs:enumeration value="neon_vfpv3" />
			<xs:enumeration value="neon-vfpv4" />
			<xs:enumeration value="neon_vfpv4" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="marketingStatusEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="preview" />
			<xs:enumeration value="Preview" />
			<xs:enumeration value="proposal" />
			<xs:enumeration value="Proposal" />
			<xs:enumeration value="new" />
			<xs:enumeration value="New" />
			<xs:enumeration value="active" />
			<xs:enumeration value="Active" />
			<xs:enumeration value="deprecated" />
			<xs:enumeration value="Deprecated" />
			<xs:enumeration value="nrnd" />
			<xs:enumeration value="Nrnd" />
			<xs:enumeration value="obsolete" />
			<xs:enumeration value="Obsolete" />
			<xs:enumeration value="st secret"/>
			<xs:enumeration value="ST Secret"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="memoryTypeEnum">
		<xs:restriction base="xs:token">
			<xs:enumeration value="ram" />
			<xs:enumeration value="rom" />
			<xs:enumeration value="flash" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="memoryStartAddressValue">
		<xs:restriction base="xs:string">
			<xs:pattern value="(0x)[0-9a-fA-F]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="memorySizeValue">
		<xs:restriction base="xs:string">
			<xs:pattern value="(0x)[0-9a-fA-F]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="memoryAlignmentValue">
		<xs:restriction base="xs:string">
			<xs:pattern value="(4|8|16|32)" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="svdElement">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="version" type="xs:string" />
			<xs:element name="url" type="xs:anyURI" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="peripheralSetElement">
		<xs:sequence>
			<xs:element name="peripheral" type="xs:Name"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CDefineSetElement">
		<xs:sequence>
			<xs:element name="CDefine" type="xs:string"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="memoryElement">
		<xs:all>
			<xs:element name="type" type="stm32:memoryTypeEnum" />
			<xs:element name="name" type="xs:string" />
			<xs:element name="address"
				type="stm32:memoryStartAddressValue" />
			<xs:element name="size" type="stm32:memorySizeValue" />
			<xs:element name="minalign"
				type="stm32:memoryAlignmentValue" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="memorySetElement">
		<xs:sequence>
			<xs:element name="memory" type="stm32:memoryElement"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="serverElement">
		<xs:sequence>
			<xs:element name="url" type="xs:anyURI"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="firmwareElement">
		<xs:all>
			<xs:element name="url" type="xs:anyURI" />
			<xs:element name="urlMd5" type="xs:string" minOccurs="0" />
			<xs:element name="patch" type="xs:anyURI" minOccurs="0" />
			<xs:element name="patchMd5" type="xs:string" minOccurs="0" />
			<xs:element name="CDefines" type="stm32:CDefineSetElement"
				minOccurs="0" />
		</xs:all>
		<xs:attribute name="type" type="stm32:firmwareTypeEnum"
			use="required" />
	</xs:complexType>


	<xs:complexType name="firmwareSetElement">
		<xs:sequence>
			<xs:element name="firmware" type="stm32:firmwareElement"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="coreElement">
		<xs:all>
			<xs:element name="type" type="stm32:cpuCoreEnum" />
			<xs:element name="fpu" type="stm32:fpuCoreEnum" />
			<xs:element name="id" type="xs:integer" />
			<xs:element name="memories" type="stm32:memorySetElement"
				minOccurs="0" />
			<xs:element name="peripherals"
				type="stm32:peripheralSetElement" minOccurs="0" />
			<xs:element name="firmwares"
				type="stm32:firmwareSetElement" minOccurs="0" />
			<xs:element name="CDefines" type="stm32:CDefineSetElement"
				minOccurs="0" />
			<xs:element name="maxFrequency" type="xs:integer"
				minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="coreSetElement">
		<xs:sequence>
			<xs:element name="core" type="stm32:coreElement"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="cpuElement">
		<xs:all>
			<xs:element name="name" type="xs:string" minOccurs="0" />
			<xs:element name="shortname" type="xs:string"
				minOccurs="0" />
			<xs:element name="id" type="xs:integer" />
			<xs:element name="memories" type="stm32:memorySetElement"
				minOccurs="0" />
			<xs:element name="peripherals"
				type="stm32:peripheralSetElement" minOccurs="0" />
			<xs:element name="firmwares"
				type="stm32:firmwareSetElement" minOccurs="0" />
			<xs:element name="CDefines" type="stm32:CDefineSetElement"
				minOccurs="0" />
			<xs:element name="cores" type="stm32:coreSetElement" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="cpuSetElement">
		<xs:sequence>
			<xs:element name="cpu" type="stm32:cpuElement"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="serieElement">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="parent" type="xs:string" />
			<xs:element name="status" type="stm32:marketingStatusEnum"
				minOccurs="0" />
			<xs:element name="svd" type="stm32:svdElement"
				minOccurs="0" />
			<xs:element name="peripherals"
				type="stm32:peripheralSetElement" minOccurs="0" />
			<xs:element name="firmwares"
				type="stm32:firmwareSetElement" minOccurs="0" />
			<xs:element name="CDefines" type="stm32:CDefineSetElement"
				minOccurs="0" />
			<xs:element name="dbgIF" type="stm32:debugInterfaceEnum"
				minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="mcuElement">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="parent" type="xs:string" />
			<xs:element name="status" type="stm32:marketingStatusEnum"
				minOccurs="0" />
			<xs:element name="svd" type="stm32:svdElement"
				minOccurs="0" />
			<xs:element name="peripherals"
				type="stm32:peripheralSetElement" minOccurs="0" />
			<xs:element name="firmwares"
				type="stm32:firmwareSetElement" minOccurs="0" />
			<xs:element name="CDefines" type="stm32:CDefineSetElement"
				minOccurs="0" />
			<xs:element name="dbgIF" type="stm32:debugInterfaceEnum"
				minOccurs="0" />
			<xs:element name="dbgDEV" type="stm32:debugDeviceEnum"
				minOccurs="0" />
			<xs:element name="memories" type="stm32:memorySetElement"
				minOccurs="0" />
			<xs:element name="cpus" type="stm32:cpuSetElement"
				minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="boardElement">
		<xs:all>
			<xs:element name="name" type="xs:string" />
			<xs:element name="parent" type="xs:string" />
			<xs:element name="status" type="stm32:marketingStatusEnum"
				minOccurs="0" />
			<xs:element name="svd" type="stm32:svdElement"
				minOccurs="0" />
			<xs:element name="peripherals"
				type="stm32:peripheralSetElement" minOccurs="0" />
			<xs:element name="firmwares"
				type="stm32:firmwareSetElement" minOccurs="0" />
			<xs:element name="CDefines" type="stm32:CDefineSetElement"
				minOccurs="0" />
			<xs:element name="dbgIF" type="stm32:debugInterfaceEnum"
				minOccurs="0" />
			<xs:element name="dbgDEV" type="stm32:debugDeviceEnum"
				minOccurs="0" />
			<xs:element name="memories" type="stm32:memorySetElement"
				minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:element name="targetParts">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="servers" type="stm32:serverElement"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="board" type="stm32:boardElement"
					maxOccurs="unbounded" />
				<xs:element name="mcu" type="stm32:mcuElement"
					maxOccurs="unbounded" />
				<xs:element name="serie" type="stm32:serieElement"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== CoolITSystemsInc/stm32cubeide/stm32cubeide/plugins/com.st.stm32cube.ide.mpu.productdb_1.0.0.201903292002/resources/board_def/stm32targets.xml
<?xml version="1.0" encoding="UTF-8"?>
<targetParts
	xsi:schemaLocation="http://openstm32.org/stm32TargetDefinitions stm32TargetDefinitions.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://openstm32.org/stm32TargetDefinitions">
	<!--version = v1.0.0 -->
  <board>
    <name>STM32MP157C-EV1</name>
    <status>ST Secret</status>
    <parent>stm32mp157caax</parent>
    <dbgDEV>st-linkv2-1</dbgDEV>
    <CDefines >
      <CDefine>-DSTM32MP15xx_EVAL</CDefine>
      <CDefine>-DSTM32MP157C_EV1</CDefine>
    </CDefines>
  </board>
  <board>
    <name>STM32MP157A-EV1</name>
    <status>ST Secret</status>
    <parent>stm32mp157aaax</parent>
    <dbgDEV>st-linkv2-1</dbgDEV>
    <CDefines >
      <CDefine>-DSTM32MP15xx_EVAL</CDefine>
      <CDefine>-DSTM32MP157A_EV1</CDefine>
    </CDefines>
  </board>
  <board>
    <name>STM32MP157C-DK2</name>
    <status>ST Secret</status>
    <parent>stm32mp157cacx</parent>
    <dbgDEV>st-linkv2-1</dbgDEV>
    <CDefines >
      <CDefine>-DSTM32MP15xx_DISCO</CDefine>
      <CDefine>-DSTM32MP157C_DK2</CDefine>
    </CDefines>
  </board>
  <board>
    <name>STM32MP157A-DK1</name>
    <status>ST Secret</status>
    <parent>stm32mp157aacx</parent>
    <dbgDEV>st-linkv2-1</dbgDEV>
    <CDefines >
      <CDefine>-DSTM32MP15xx_DISCO</CDefine>
      <CDefine>-DSTM32MP157A_DK1</CDefine>
    </CDefines>
  </board>
	

  <mcu>
    <name>STM32MP151AAAx</name>
    <status>ST Secret</status>
    <parent>stm32mp1</parent>
		<cpus>
			<cpu>
				<name>Co-Pro ARM Cortex-M4</name>
				<shortname>CM4</shortname>
				<id>0</id>
				<cores>
					<core>
						<id>0</id>
						<type>arm cortex-m4</type>
						<fpu>fpv4-sp-d16</fpu>
						<maxFrequency>216000</maxFrequency>
					</core>
				</cores>
			</cpu>
			<cpu>
				<name>Main-Pro dual ARM Cortex-A7</name>
				<shortname>x2CA7</shortname>
				<id>1</id>
				<cores>
					<core>
						<id>1</id>
						<type>arm cortex-a7</type>
						<fpu>vfpv4_d16</fpu>
						<maxFrequency>1000000</maxFrequency>
					</core>
					<core>
						<id>2</id>
						<type>arm cortex-a7</type>
						<fpu>vfpv4_d16</fpu>
						<maxFrequency>1000000</maxFrequency>
					</core>
				</cores>
			</cpu>
		</cpus>
    <memories >
      <memory>
		<type>ram</type>
        <name>RAM</name>
        <address>0x10000000</address>
        <!--size from xml = 0x0-->
        <size>0x40000</size>
        <!--end = 0x0-->
      </memory>
      <memory>
		<type>ram</type>
        <name>RETRAM</name>
        <address>0x00000000</address>
        <size>0x10000</size>
        <!--end = 0x0-->
      </memory>
    </memories>
    <svd>
     <name>STM32MP15xxx.svd</name>
      <version>v1r2</version>
      <url></url>
    </svd>
    <CDefines >
      <CDefine>-DSTM32MP15xx</CDefine>
      <CDefine>-DSTM32MP151AAAx</CDefine>
    </CDefines>
    <peripherals >
      <peripheral>ADC1</peripheral>
      <peripheral>ADC2</peripheral>
      <peripheral>BSEC</peripheral>
      <peripheral>CRC1</peripheral>
      <peripheral>CRC2</peripheral>
      <peripheral>DAC1</peripheral>
      <peripheral>DBGMCU</peripheral>
      <peripheral>DCMI</peripheral>
      <peripheral>DDR</peripheral>
      <peripheral>DFSDM1</peripheral>
      <peripheral>DTS</peripheral>
      <peripheral>ETH1</peripheral>
      <peripheral>ETZPC</peripheral>
      <peripheral>FMC</peripheral>
      <peripheral>FREERTOS</peripheral>
      <peripheral>HASH1</peripheral>
      <peripheral>HASH2</peripheral>
      <peripheral>HDMI_CEC</peripheral>
      <peripheral>HDP</peripheral>
      <peripheral>HSEM</peripheral>
      <peripheral>I2C1</peripheral>
      <peripheral>I2C2</peripheral>
      <peripheral>I2C3</peripheral>
      <peripheral>I2C4</peripheral>
      <peripheral>I2C5</peripheral>
      <peripheral>I2C6</peripheral>
      <peripheral>I2S1</peripheral>
      <peripheral>I2S2</peripheral>
      <peripheral>I2S3</peripheral>
      <peripheral>IPCC</peripheral>
      <peripheral>IWDG1</peripheral>
      <peripheral>IWDG2</peripheral>
      <peripheral>LPTIM1</peripheral>
      <peripheral>LPTIM2</peripheral>
      <peripheral>LPTIM3</peripheral>
      <peripheral>LPTIM4</peripheral>
      <peripheral>LPTIM5</peripheral>
      <peripheral>LTDC</peripheral>
      <peripheral>OPENAMP</peripheral>
      <peripheral>PWR</peripheral>
      <peripheral>QUADSPI</peripheral>
      <peripheral>RCC</peripheral>
      <peripheral>RESMGR_UTILITY</peripheral>
      <peripheral>RNG1</peripheral>
      <peripheral>RNG2</peripheral>
      <peripheral>RTC</peripheral>
      <peripheral>SAI1</peripheral>
      <peripheral>SAI2</peripheral>
      <peripheral>SAI3</peripheral>
      <peripheral>SAI4</peripheral>
      <peripheral>SDMMC1</peripheral>
      <peripheral>SDMMC2</peripheral>
      <peripheral>SDMMC3</peripheral>
      <peripheral>SPDIFRX</peripheral>
      <peripheral>SPI1</peripheral>
      <peripheral>SPI2</peripheral>
      <peripheral>SPI3</peripheral>
      <peripheral>SPI4</peripheral>
      <peripheral>SPI5</peripheral>
      <peripheral>SPI6</peripheral>
      <peripheral>SYS</peripheral>
      <peripheral>TAMP</peripheral>
      <peripheral>TIM1</peripheral>
      <peripheral>TIM2</peripheral>
      <peripheral>TIM3</peripheral>
      <peripheral>TIM4</peripheral>
      <peripheral>TIM5</peripheral>
      <peripheral>TIM6</peripheral>
      <peripheral>TIM7</peripheral>
      <peripheral>TIM8</peripheral>
      <peripheral>TIM12</peripheral>
      <peripheral>TIM13</peripheral>
      <peripheral>TIM14</peripheral>
      <peripheral>TIM15</peripheral>
      <peripheral>TIM16</peripheral>
      <peripheral>TIM17</peripheral>
      <peripheral>UART4</peripheral>
      <peripheral>UART5</peripheral>
      <peripheral>UART7</peripheral>
      <peripheral>UART8</peripheral>
      <peripheral>USART1</peripheral>
      <peripheral>USART2</peripheral>
      <peripheral>USART3</peripheral>
      <peripheral>USART6</peripheral>
      <peripheral>USBH_HS1</peripheral>
      <peripheral>USBH_HS2</peripheral>
      <peripheral>USB_OTG_HS</peripheral>
      <peripheral>VREFBUF</peripheral>
      <peripheral>WWDG1</peripheral>
      <peripheral>GPIO</peripheral>
    </peripherals>
  </mcu>

  <mcu>
    <name>STM32MP151AABx</name>
    <status>ST Secret</status>
    <parent>stm32mp1</parent>
		<cpus>
			<cpu>
				<name>Co-Pro ARM Cortex-M4</name>
				<shortname>CM4</shortname>
				<id>0</id>
				<cores>
					<core>
						<id>0</id>
						<type>arm cortex-m4</type>
						<fpu>fpv4-sp-d16</fpu>
						<maxFrequency>216000</maxFrequency>
					</core>
				</cores>
			</cpu>
			<cpu>
				<name>Main-Pro dual ARM Cortex-A7</name>
				<shortname>x2CA7</shortname>
				<id>1</id>
				<cores>
					<core>
						<id>1</id>
						<type>arm cortex-a7</type>
						<fpu>vfpv4_d16</fpu>
						<maxFrequency>1000000</maxFrequency>
					</core>
					<core>
						<id>2</id>
						<type>arm cortex-a7</type>
						<fpu>vfpv4_d16</fpu>
						<maxFrequency>1000000</maxFrequency>
					</core>
				</cores>
			</cpu>
		</cpus>
    <memories >
      <memory>
		<type>ram</type>
        <name>RAM</name>
        <address>0x10000000</address>
        <!--size from xml = 0x0-->
        <size>0x40000</size>
        <!--end = 0x0-->
      </memory>
      <memory>
		<type>ram</type>
        <name>RETRAM</name>
        <address>0x00000000</address>
        <size>0x10000</size>
        <!--end = 0x0-->
      </memory>
    </memories>
    <svd>
     <name>STM32MP15xxx.svd</name>
      <version>v1r2</version>
      <url></url>
    </svd>
    <CDefines >
      <CDefine>-DSTM32MP15xx</CDefine>
      <CDefine>-DSTM32MP151AABx</CDefine>
    </CDefines>
    <peripherals >
      <peripheral>ADC1</peripheral>
      <peripheral>ADC2</peripheral>
      <peripheral>BSEC</peripheral>
      <peripheral>CRC1</peripheral>
      <peripheral>CRC2</peripheral>
      <peripheral>DAC1</peripheral>
      <peripheral>DBGMCU</peripheral>
      <peripheral>DCMI</peripheral>
      <peripheral>DDR</peripheral>
      <peripheral>DFSDM1</peripheral>
      <peripheral>DTS</peripheral>
      <peripheral>ETH1</peripheral>
      <peripheral>ETZPC</peripheral>
      <peripheral>FMC</peripheral>
      <peripheral>FREERTOS</peripheral>
      <peripheral>HASH1</peripheral>
      <peripheral>HASH2</peripheral>
      <peripheral>HDMI_CEC</peripheral>
      <peripheral>HDP</peripheral>
      <peripheral>HSEM</peripheral>
      <peripheral>I2C1</peripheral>
      <peripheral>I2C2</peripheral>
      <peripheral>I2C3</peripheral>
      <peripheral>I2C4</peripheral>
      <peripheral>I2C5</peripheral>
      <peripheral>I2C6</peripheral>
      <peripheral>I2S1</peripheral>
      <peripheral>I2S2</peripheral>
      <peripheral>I2S3</peripheral>
      <peripheral>IPCC</peripheral>
      <peripheral>IWDG1</peripheral>
      <peripheral>IWDG2</peripheral>
      <peripheral>LPTIM1</peripheral>
      <peripheral>LPTIM2</peripheral>
      <peripheral>LPTIM3</peripheral>
      <peripheral>LPTIM4</peripheral>
      <peripheral>LPTIM5</peripheral>
      <peripheral>LTDC</peripheral>
      <peripheral>OPENAMP</peripheral>
      <peripheral>PWR</peripheral>
      <peripheral>QUADSPI</peripheral>
      <peripheral>RCC</peripheral>
      <peripheral>RESMGR_UTILITY</peripheral>
      <peripheral>RNG1</peripheral>
      <peripheral>RNG2</peripheral>
      <peripheral>RTC</peripheral>
      <peripheral>SAI1</peripheral>
      <peripheral>SAI2</peripheral>
      <peripheral>SAI3</peripheral>
      <peripheral>SAI4</peripheral>
      <peripheral>SDMMC1</peripheral>
      <peripheral>SDMMC2</peripheral>
      <peripheral>SDMMC3</peripheral>
      <peripheral>SPDIFRX</peripheral>
      <peripheral>SPI1</peripheral>
      <peripheral>SPI2</peripheral>
      <peripheral>SPI3</peripheral>
      <peripheral>SPI4</peripheral>
      <peripheral>SPI5</peripheral>
      <peripheral>SPI6</peripheral>
      <peripheral>SYS</peripheral>
      <peripheral>TAMP</peripheral>
      <peripheral>TIM1</peripheral>
      <peripheral>TIM2</peripheral>
